### ISSUE TITLE
TODO: Come up with a better Ip address system

### ISSUE THREAD

**Issue by GRVYDEV** [GRVYDEV/Lightspeed-ingest#10]
As of right now the local IP is hard coded. Either refactor to take this as an argument or grab it from the system

**Comment by aberrios85** [comment]
I'm thinking create a config.rs module... handle the config in there exposing a global config const from a config struct. 

Using `config-rs` if you want a config file/ env vars driven configuration or `clap` for command line args driven. Personally I prefer `config-rs`. Let me know your thoughts, I'll see if I can PR it at the weekend.

**Comment by GRVYDEV** [comment]
> I'm thinking create a config.rs module... handle the config in there exposing a global config const from a config struct.
> 
> Using `config-rs` if you want a config file/ env vars driven configuration or `clap` for command line args driven. Personally I prefer `config-rs`. Let me know your thoughts, I'll see if I can PR it at the weekend.

config-rs would be nice for the stream key as well. It just needs to be configurable from docker as well

**Comment by GRVYDEV** [comment]
Closing as this has been remedied by [this](https://github.com/GRVYDEV/Lightspeed-ingest/pull/26) commit! @aberrios85 I'm sorry you didn't get to take a crack at this one but that you for being willing and there will definitely be more things in the future!

**Comment by GRVYDEV** [comment]
Closing as this has been remedied by [this](https://github.com/GRVYDEV/Lightspeed-ingest/pull/26) commit! @aberrios85 I'm sorry you didn't get to take a crack at this one but thank you for being willing and there will definitely be more things in the future!
