### ISSUE TITLE
TODO: Better stream key system

### ISSUE THREAD

**Issue by GRVYDEV** [GRVYDEV/Lightspeed-ingest#11]
As of right now the stream key is hard coded. This is insecure and not production ready.

IDEAS:

-On first time startup create a stream key and cache it on the system. This will then be output to the user in order to put into obs. This will need to support the ability to generate a new key in case it gets leaked

-Take the stream key as an argument and allow the orchestrator to handle it

**Comment by obviyus** [comment]
I really like the sound of the first approach. Do you mind if I work on this?

**Comment by GRVYDEV** [comment]
> I really like the sound of the first approach. Do you mind if I work on this?

Go ahead :D
