### ISSUE TITLE
TODO: CI/CD Workflow - Docker Image Generation

### ISSUE THREAD

**Issue by brettwilcox** [GRVYDEV/Lightspeed-ingest#15]
### GitHub Workflow to generate binary

It would simplify the docker images greatly if we already have a binary available to pull from GitHub. I found the below repository a good reference for a rust binary generator.

https://github.com/Peltoche/lsd/blob/master/.github/workflows/CICD.yml

**Comment by GRVYDEV** [comment]
Yup this is a great idea! We can also do this for Lightspeed-webrtc as well since Go compiles to a binary

**Comment by Crowdedlight** [comment]
I'm playing around making a docker and docker-compose as I want to deploy this for a small group of friends on my server. My current branch is here: https://github.com/Crowdedlight/Project-Lightspeed/tree/feature/docker 

All three containers build and run. However I'm still trying to figure out the network connections needed between host and in between the containers. 

I'm by no means a docker expert, and from what you have linked here and from examples in https://github.com/GRVYDEV/Project-Lightspeed/issues/2 I can see there is smarter ways to pull the binaries than building them as I currently do ;-)

**Comment by GRVYDEV** [comment]
> I'm playing around making a docker and docker-compose as I want to deploy this for a small group of friends on my server. My current branch is here: https://github.com/Crowdedlight/Project-Lightspeed/tree/feature/docker
> 
> All three containers build and run. However I'm still trying to figure out the network connections needed between host and in between the containers.
> 
> I'm by no means a docker expert, and from what you have linked here and from examples in [GRVYDEV/Project-Lightspeed#2](https://github.com/GRVYDEV/Project-Lightspeed/issues/2) I can see there is smarter ways to pull the binaries than building them as I currently do ;-)

So here is the network config. Ingest needs to listen on port 8084, WebRTC needs to listen on port 65535 and then host on port 8080, lightspeed react needs port 80

**Comment by GRVYDEV** [comment]
Renamed since we will opt for docker image generation here instead of binary (we may revisit binary in the future if there is enough demand)

**Comment by GRVYDEV** [comment]
This has been implemented. Upon a version tagged commit a docker image will be generated and deployed [here](https://hub.docker.com/repository/docker/projectlightspeed/ingest)

**Comment by GRVYDEV** [comment]
This has been implemented. Upon a version tagged commit a docker image will be generated and deployed [here](https://hub.docker.com/repository/docker/projectlightspeed/ingest)
