### ISSUE TITLE
Request: add logging output to file as well as console

### ISSUE THREAD

**Issue by armlesshobo** [GRVYDEV/Lightspeed-ingest#28]
Consider adding support to log output to both a file and console.

1.) support log output to a file
 - allow user to provide log file location using command line argument (maybe env var?)
 
2.) support console logging

3.) allow user to specify log level with a command line argument (maybe env var also?)
 - default to Info?

Thinking about log formatting, It would make sense to start with a simple format now, and make adjustments in later iterations.

**Comment by GRVYDEV** [comment]
Yeah I definitely think this is needed! We should also do this for Lightspeed-webrtc

**Comment by GRVYDEV** [comment]
Closed with [this](https://github.com/GRVYDEV/Lightspeed-ingest/pull/30) commit
