### ISSUE TITLE
720p messages in ingest container

### ISSUE THREAD

**Issue by ambustion** [GRVYDEV/Lightspeed-ingest#38]
I'm having trouble telling whether this is an obs issue or what is being reported in my ingest container, but it only ever reports a 720p stream. 

If I change the stream size in obs, it will load the image smaller in the webpage, so I think it is sending a smaller stream, but no matter what, the console always says 720P. I was trying to confirm that I could get 1080P.

**Comment by GRVYDEV** [comment]
I can confirm that this is an FTL issue however you are able to send whatever size video you want. It will always report 720p
