### ISSUE TITLE
UDP Cast Error

### ISSUE THREAD

**Issue by GRVYDEV** [GRVYDEV/Lightspeed-ingest#7]
When negotiating the port with the FTL client the client errors out and uses the default port of 65535. This needs to be debugged and fixed. 

NOTE:
Use tcpdump to check the handshake and see what is being sent to the client

**Comment by Jokler** [comment]
I am currently trying to figure this out, so far I found that the following is sent by Lightspeed-ingest and received by OBS as the answer to `FtlCommand::Dot`:
```
200
200
200
200
200
200
200
200
200
200
200
200
200 hi. Use UDP port 65535


```

ftl-sdk then accepts `200` as the response since it drops everything after the first newline which results in it not finding the port.

**Comment by GRVYDEV** [comment]
Afaik the format of the commands is **respcode data** so 200 hi. Use UDP port 65535 should work. The client reads until it sees a \n

**Comment by GRVYDEV** [comment]
> I am currently trying to figure this out, so far I found that the following is sent by Lightspeed-ingest and received by OBS:
> 
> ```
> 200
> 200
> 200
> 200
> 200
> 200
> 200
> 200
> 200
> 200
> 200
> 200
> 200 hi. Use UDP port 65535
> ```
> 
> ftl-sdk then accepts `200` as the response since it drops everything after the first newline which results in it not finding the port.

Also the ingest is supposed to be sending 200 hi. Use UDP port 10170\n

**Comment by Jokler** [comment]
>200 hi. Use UDP port 65535 should work

I understand that, but it is not what I see when I print the buffer in ftl-sdk so something must have gone wrong. You can confirm that easily in Wireshark.

>Also the ingest is supposed to be sending 200 hi. Use UDP port 10170\n

Oh, that's my bad, i changed the number in the rust code.

**Comment by GRVYDEV** [comment]
> > 200 hi. Use UDP port 65535 should work
> 
> I understand that, but it is not what I see when I print the buffer in ftl-sdk so something must have gone wrong. You can confirm that easily in Wireshark.
> 
> > Also the ingest is supposed to be sending 200 hi. Use UDP port 10170\n
> 
> Oh, that's my bad, i changed the number in the rust code.

Hmmm so is the 200 supposed to come after the data?

**Comment by Jokler** [comment]
You misunderstand, your code looks right to me too. The program ends up not sending what you expect it to be sending though.

**Comment by GRVYDEV** [comment]
> > 200 hi. Use UDP port 65535 should work
> 
> I understand that, but it is not what I see when I print the buffer in ftl-sdk so something must have gone wrong. You can confirm that easily in Wireshark.
> 
> > Also the ingest is supposed to be sending 200 hi. Use UDP port 10170\n
> 
> Oh, that's my bad, i changed the number in the rust code.

Or it could be caused by sending a 200\n after the last attribute command

**Comment by Jokler** [comment]
How would that send `200\n` twelve times?

**Comment by Jokler** [comment]
I see why you were confused by my first reply and edited it.
The entire thing is the packet you seem to be sending to reply to `.`.

**Comment by GRVYDEV** [comment]
> I see why you were confused by my first reply and edited it.
> The entire thing is the packet you seem to be sending to reply to `.`.

Okay that is a bug then. It is not supposed to send 12 200s. This means that I may not need to respond with 200\n to the attribute commands and they must be building up in the write buffer and then once the attributes are done it is sending the entire buffer.

**Comment by Jokler** [comment]
I realize now it might be a bit more helpful for you to have the entire TCP stream as wireshark saw it.

```
HMAC

200 2eb0945244b61c8b1bada95b7a751880975c970a19951f07423c0cb1377bba3144146f8389b6ac5d8b553bb9c6ad5e8d6cb21d10288ddd1386bdeaa7af6f68a1277de4a467b2a56455850ac3969a4e69c17be4ba12bb56812b302a4e5645ca970edc047244ab72c44732f3472922ea4835e573f656707a423496069832ef858c
CONNECT 13 $2315752d39fd01e864405c92585d1188f202c8daad40d3f6850e5045a966640f35d0a8564762f81ae28e87771bee0318d518990eec22721b1496b25c13b5fc1e

200
ProtocolVersion: 0.9

VendorName: OBS Studio

VendorVersion: 26.1.0.r44.gdffa82211

Video: true

VideoCodec: H264

VideoHeight: 720

VideoWidth: 1280

VideoPayloadType: 96

VideoIngestSSRC: 14

Audio: true

AudioCodec: OPUS

AudioPayloadType: 97

AudioIngestSSRC: 13

.

200
200
200
200
200
200
200
200
200
200
200
200
200
200 hi. Use UDP port 10170
PING 13

201
DISCONNECT

```

Seeing it like this now my guess is that you are only supposed to send one 200 at the end?

**Comment by GRVYDEV** [comment]
This is a very easy fix! In the `handle_command` function under the attribute command arm just remove this code

```
resp.push("200\n".to_string());
       match sender.send(FrameCommand::Send { data: resp }).await {
               Ok(_) => {
                      return;
                }
               Err(e) => println!(
                     "Error sending to frame task (From: Handle Connection) {:?}",
                         e
                     ),
             }
```

**Comment by Jokler** [comment]
It looks like it should respond to the stream key with 200. After that the [TRUE/FALSE](https://github.com/mixer/ftl-sdk/blob/d0c8469f66806b5ea738d607f7d2b000af8b1129/libftl/handshake.c#L157-L219) corresponds to `need_response` for each command.

Edit: My bad, that's exactly what you said and I just did not understand.

**Comment by GRVYDEV** [comment]
> It looks like it should respond to the stream key with 200. After that the [TRUE/FALSE](https://github.com/mixer/ftl-sdk/blob/d0c8469f66806b5ea738d607f7d2b000af8b1129/libftl/handshake.c#L157-L219) corresponds to `need_response` for each command.

This is weird because it looks like they're checking that the response code for each attribute is = to FTL_RESP_OK which would be 200

**Comment by Jokler** [comment]
It starts out like that and only if `needed_response` is `TRUE` they read the response.
https://github.com/mixer/ftl-sdk/blob/d0c8469f66806b5ea738d607f7d2b000af8b1129/libftl/handshake.c#L345

**Comment by Jokler** [comment]
I figured it out, why it still wasn't working. I'll make a PR.

**Comment by GRVYDEV** [comment]
> I figured it out, why it still wasn't working. I'll make a PR.

Great! Thank you! This was such an annoying error that I was just putting it off till I got some other things done first
